### ISSUE TITLE
Delete cluster seems to be taking too long to complete

### ISSUE THREAD

**Issue by jachermocilla** [vincentpaul12/SkyLab#5]
Cluster name 	Nodes 	IP address 	Tasks queued 	Status 	Share key 	Visibility 	Date created
jach_skylab 	2 	10.0.3.239 	0 	Online (Scheduled for deletion) 	Y6HLJ 	
	11/14/2016 4:44 p.m.

**Comment by vincentpaul12** [comment]
Tingnan ko po sir.

**Comment by vincentpaul12** [comment]
Nakita ko na po yung error sir blocking yung queue.get() ko kaya hindi siya nagtothrow ng exception para magdelete.

**Comment by vincentpaul12** [comment]
Fixed na sir. Update ko na lang mamaya yung server pagkatapos ng iba pa
